### ISSUE TITLE
Test Script produces Error

### ISSUE THREAD

**Issue by schmistenew** [Ragin-LundF/telegraf_fritzbox_monitor#3]
Hi,
I've checked your fork of the original one, as I'm using it.
If I run the test script I'm getting a bunch of errors.

```
python3 /opt/telegraf_fritzbox/telegraf_fritzbox.py -i 192.168.0.107 -u USERNAME -p PASSWORD
FritzBox,host=(none),source=general ModelName="FRITZ!Box 7530",Firmware="7.29",WANAccessType="None",SerialNumber="xxxxxxxxxxx"
Traceback (most recent call last):
  File "/opt/telegraf_fritzbox/telegraf_fritzbox.py", line 88, in <module>
    execute()
  File "/opt/telegraf_fritzbox/telegraf_fritzbox.py", line 77, in execute
    influxp.print("status", FritzboxConnectStatus(fritz_connect).stats().influx_data())
  File "/opt/telegraf_fritzbox/modules/general/fritzbox_status.py", line 12, in stats
    uptime=self.uptime(),
  File "/opt/telegraf_fritzbox/modules/general/fritzbox_status.py", line 20, in uptime
    return self.__FC_STATUS.device_uptime
AttributeError: 'FritzStatus' object has no attribute 'device_uptime'
```

If you need some further information, feel free to contact me.
Regards Stephan

**Comment by Ragin-LundF** [comment]
It seems to be an issue with the `fritzconnection` version.
I've changed the requirements.txt file to use the minimal version 1.9.1 (currently latest).
Can you please pull the change and do a `pip3 install -r requirements.txt` again and check, if it solves the issue?

If it doesn't help, please check which version you are using.
This can be done for example with

```bash
pip install pipdeptree
pipdeptree
```

Thanks!

**Comment by schmistenew** [comment]
I was able to upgrade firtzconnection to the newest version, now it works.
