### ISSUE TITLE
InfluxDB2

### ISSUE THREAD

**Issue by frankhausmannpetri** [Ragin-LundF/telegraf_fritzbox_monitor#8]
i´ve updated my Influxdb from 1.8 to 2.6 so my Fritzbox monitoring dosn´t work now. wich Changes i have to make in my  .conf file ? Please help

**Comment by Ragin-LundF** [comment]
I tried it with InfluxDB2 and it works.
The question is, how did you connect Grafana?
With a token to user mapping and as InfluxQL or as Flux?

In the case of Flux, all queries need to be customized.
For this case, I am looking at providing an updated dashboard.

**Comment by Ragin-LundF** [comment]
I've added a new Grafana template.
Please check out, if it works correct.

I tried to compare with the old version, and it looks good so far, but I've changed some parts in my network, so there might be some issues.
If you find something, please open a new issue :).
